name: Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.20.2
        uses: actions/setup-node@v1
        with:
          node-version: 18.20.2

      - name: Install Packages
        run: |
          npm install

      - name: npm build
        run: npm run build

      - name: run Lighthouse CI 
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun
